// Code generated by goctl. DO NOT EDIT.
package types

type Goods struct {
	GoodsID int64 `json:"goodsId"`
	Num     int64 `json:"num"`
}

type OrderCreateRequest struct {
	UserID int64   `json:"userId"`
	Goods  []Goods `json:"goods"`
}

type OrderCreateResponse struct {
	Url string `json:"url"`
}

type OrderNofitRequest struct {
}

type OrderNofitResponse struct {
	Message string `json:"message"`
}
