// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"zg6/z326/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/create/v1",
				Handler: OrderCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/nofit/v1",
				Handler: OrderNofitHandler(serverCtx),
			},
		},
	)
}
